import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1400, height: 900 } });
await page.goto('https://tenancymate.vercel.app');
await page.getByRole('button', { name: /weeks of bond/ }).click();
await page.getByRole('button', { name: 'Send' }).click();
await page.waitForSelector('aside [data-section]', { timeout: 120000 });
const answer = await page.locator('.rounded-lg.border').first().textContent();
console.log('PROD ANSWER:', answer.slice(0, 200));
const panel = await page.$$eval('aside [data-section]', els => els.map(e => e.getAttribute('data-section')));
console.log('panel:', panel.join(','));
await browser.close();
